INSERT INTO salas (nombre, ubicacion, cantidad_filas, cantidad_columnas) VALUES
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4),
('Van Rossum', 'Segundo piso, al lado de las escaleras, Riwi', 10, 4),
('Meta', 'Segundo piso, al lado contrario de las escaleras, Riwi', 10, 4),
('Lovelace', 'Tercer piso, al lado de las escaleras, Riwi', 10, 4);
